INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Roberto Canales','Curso TDD',15,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Roberto Canales','Novedades Java 8',15,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Introducción al lenguaje Java',20,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Desarrollo de Aplicaciones Web en Java',20,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Conceptos avanzados de desarrollo Java',20,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Arquitectura de Aplicaciones Empresariales Java: JEE',15,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Novedades de Java 7.0',10,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Roberto Canales','Java y Patrones de Diseño',15,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Roberto Canales','Desarrollo de pruebas unitarias en Java',15,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Buenas prácticas en el desarrollo de aplicaciones Java',15,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Web Services sobre plataforma Java',20,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Roberto Canales','Seguridad en Java',25,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Construcción de aplicaciones con Maven',10,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (false,'Roberto Canales','Control de versiones con SubVersion/CVS',15,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Generación de informes con JasperReports/iReport',15,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Integración de plataformas con arquitecturas ESB: Mule',20,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Arquitecturas Orientadas a Servicios: SOA',15,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Desarrollo de aplicaciones Ajax',15,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Roberto Canales','Desarrollo de aplicaciones Web con Spring',15,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (false,'Angel Ruiz','Introducción a JSF',15,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (false,'Alberto Moratilla','Introducción a Struts',15,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Acceso a datos con Hibernate',15,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (false,'Roberto Canales','Acceso a datos con MyBatis',15,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','El motor de bœsqueda Solr',25,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Maven + Spring + Hibernate + EJB',25,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (false,'Roberto Canales','Maven + JSF + Ajax + Facelets + EJB 3.0',20,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Administración y despliegue de aplicaciones con JBoss',15,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Fundamentos de Scala',20,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Pruebas de aceptación para aplicaciones Web',20,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Metodologías Ágiles: construye software como las empresas de éxito',15,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Dirección de Proyectos y Gestión Eficiente de Equipos',15,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Roberto Canales','Gestión de Requisitos en Proyectos Informáticos',20,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Gestión eficaz del tiempo y eficacia personal',25,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Metodologías Ágiles: Scrum, Kanban',25,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Introducción a las nuevas tecnologías',15,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Introducción a la Orientación a Objetos',15,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Roberto Canales','Análisis y diseño orientado a objetos con UML 2.x',25,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Accesibilidad Web',10,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Desarrollo de páginas Web: HTML 5, CSS 3, JavaScript',10,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Introducción a la Gestión de Contenidos',15,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Desarrollo de aplicaciones con Liferay',20,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Administración de Liferay',20,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Desarrollo de aplicaciones con Alfresco',25,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Administración de Alfresco',20,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Programación de aplicaciones sobre iPhone',10,1);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Programación de aplicaciones sobre Android',10,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Alberto Moratilla','Desarrollo de aplicaciones con C/C++',15,3);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Roberto Canales','Introducción a MySQL',15,2);
INSERT INTO TRAINING.course (active,teacher,title,hours,level) VALUES (true,'Angel Ruiz','Introducción a Linux',15,3);
COMMIT;